#! /bin/sh
module load \
    CMake/3.15.3-GCCcore-8.3.0 \
    OpenMPI/3.1.4-GCC-8.3.0 \
    gperftools/2.7.90-GCCcore-8.3.0
case $1 in
"load") ;;
"clean")
    rm -rf build
    mkdir build
    rm -rf bin
    mkdir bin
    ;;
"build")
    cd build
    cmake -DCMAKE_BUILD_TYPE=Release ..
    make -j6
    ;;
"buildTick")
    cd build
    cmake -DCMAKE_BUILD_TYPE=Release -DTicktock=Ticktock ..
    make -j6
    ;;
"debug")
    cd build
    cmake -DCMAKE_BUILD_TYPE=Debug ..
    make -j6
    ;;
"make")
    cd build
    make
    ;;
"run")
    cd timeCompare
    starttime=$(date +'%Y-%m-%d %H:%M:%S')
    # ../bin/SiprosV3omp -c ../../data/SiproConfig.N15_0Pct.cfg \
    #     -f ../../data/AMD_DynamicSIP_SampleD_TimePoint0_BRmixed_WC_Velos_OrbiMS2_Run2_020210_09.FT2 \
    #     -o . -s
    ../bin/SiprosV3omp -c ../../data/SiproConfig.Ecoli.C13.cfg \
        -f /ourdisk/hpc/prebiotics/yixiong/auto_archive_notyet/ubuntuShare/EcoliSIP/C13pct50orbit90min/ft/Pan_052322_X13.FT2 \
        -o . -s
    endtime=$(date +'%Y-%m-%d %H:%M:%S')
    start_seconds=$(date --date="$starttime" +%s)
    end_seconds=$(date --date="$endtime" +%s)
    echo "running time： "$((end_seconds - start_seconds))"s"
    ;;
*)
    ./make "build"
    ;;
esac
