# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simple peak calculator of natural isotopic distribution
#' @param AAstr a CharacterVector
#' @export
peak_calculator <- function(AAstr) {
    .Call(`_AAisoPeak_peak_calculator`, AAstr)
}

#' Simple peak calculator of user defined isotopic distribution
#' @param AAstr a CharacterVector
#' @param Atom a CharacterVector C13 or N15
#' @param Prob a NumericVector for its abundance
#' @export
peak_calculator_DIY <- function(AAstr, Atom, Prob) {
    .Call(`_AAisoPeak_peak_calculator_DIY`, AAstr, Atom, Prob)
}

#' Simple sum
#' @param x a numeric vector
#' @export
calc_sum <- function(x) {
    .Call(`_AAisoPeak_calc_sum`, x)
}

