# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' getUnfilteredPeptides
#' @param workingPath a full path with .sip files in it
#' @return a dataframe of unique peptides and whether it is decoy sequence
#' @export
getUnfilteredPeptides <- function(workingPath) {
    .Call(`_AAisoPeak_getUnfilteredPeptides`, workingPath)
}

#' getFilterThreshold
#' @param workingPath a full path with .sip files in it
#' @return a dataframe about filter threshold and FDR results
#' @export
getFilterThreshold <- function(workingPath, OverallThreshold) {
    .Call(`_AAisoPeak_getFilterThreshold`, workingPath, OverallThreshold)
}

#' Simple peak calculator of natural isotopic distribution
#' @param AAstr a CharacterVector
#' @export
peak_calculator <- function(AAstr) {
    .Call(`_AAisoPeak_peak_calculator`, AAstr)
}

#' Simple peak calculator of user defined isotopic distribution
#' @param AAstr a CharacterVector
#' @param Atom a CharacterVector C13 or N15
#' @param Prob a NumericVector for its abundance
#' @export
peak_calculator_DIY <- function(AAstr, Atom, Prob) {
    .Call(`_AAisoPeak_peak_calculator_DIY`, AAstr, Atom, Prob)
}

#' readOneScanMS2
#' @param ftFile a ft2 file's full path
#' @param scanCount the scanCount'th scan
#' @export
readOneScanMS2 <- function(ftFile, scanCount) {
    .Call(`_AAisoPeak_readOneScanMS2`, ftFile, scanCount)
}

#' readOneScanMS1
#' @param ftFile a ft1 file's full path
#' @param scanCount the scanCount'th scan
#' @export
readOneScanMS1 <- function(ftFile, scanCount) {
    .Call(`_AAisoPeak_readOneScanMS1`, ftFile, scanCount)
}

#' readScansMS1
#' @param ftFile a ft1 file's full path
#' @param scanNumber the scanNumber th scan
#' @export
readScansMS1 <- function(ftFile, scanCount) {
    .Call(`_AAisoPeak_readScansMS1`, ftFile, scanCount)
}

#' readAllScanMS1
#' @param ftFile a ft1 file's full path
#' @export
readAllScanMS1 <- function(ftFile) {
    .Call(`_AAisoPeak_readAllScanMS1`, ftFile)
}

#' readScansMS2
#' @param ftFile a ft2 file's full path
#' @param scanNumber the scanNumber th scan
#' @export
readScansMS2 <- function(ftFile, scanCount) {
    .Call(`_AAisoPeak_readScansMS2`, ftFile, scanCount)
}

#' readAllScanMS2
#' @param ftFile a ft1 file's full path
#' @export
readAllScanMS2 <- function(ftFile) {
    .Call(`_AAisoPeak_readAllScanMS2`, ftFile)
}

#' readSip
#' @param sipFile a .sip file's full path
#' @export
readSip <- function(sipFile) {
    .Call(`_AAisoPeak_readSip`, sipFile)
}

#' readSips
#' @param workingPath a full path with .sip files in it
#' @export
readSips <- function(workingPath) {
    .Call(`_AAisoPeak_readSips`, workingPath)
}

#' Simple sum
#' @param x a numeric vector
#' @export
calc_sum <- function(x) {
    .Call(`_AAisoPeak_calc_sum`, x)
}

#' test ftFileReader
#' @param ftFile a ft file's full path
#' @export
test_ftFileReader <- function(ftFile) {
    invisible(.Call(`_AAisoPeak_test_ftFileReader`, ftFile))
}

