[Including C++ code in a Subdirectory within the Src Directory](https://github.com/r-pkg-examples/rcpp-headers-subdirs)\
[Rcpp read file in package](https://stackoverflow.com/questions/52979101/acessing-data-on-inst-extdata-from-rcpp-catch-tests)\
[R read file in package](https://stackoverflow.com/questions/11977417/package-relative-paths-in-r)\
[debug Rcpp in vscode](https://github.com/renkun-ken/vscode-rcpp-demo)\
[R-package development](https://blog.csdn.net/Xiaoyi_Zhang/article/details/79999348)\
[R package for MS](https://www.bioconductor.org/packages/release/data/experiment/vignettes/RforProteomics/inst/doc/RProtVis.html#Visualisation_of_proteomics_data_using_R_and_Bioconductor)\
[mzR package](https://github.com/sneumann/mzR/)

## for analyze

```{r}
# run test
devtools::test()
# load all function
devtools::clean_dll()
devtools::load_all()
# generate document
devtools::document()

system.time(a <-
              readScansMS1("/mnt/d/work/202202/testRAW/201019_CP_6801_E50.FT1", 10000))
sprintf("%.3f", a[[1]]$TIC)
sprintf("%.9f", a[[1]]$peaks[1, 1])
system.time(a <-
              readScansMS2("/mnt/d/work/202202/testRAW/201019_CP_6801_E50.FT2", 10000))

system.time(b <-
              readAllScanMS1("/mnt/d/work/202202/testRAW/201019_CP_6801_E50.FT1"))
sprintf("%.3f", b$`26`$TIC)
sprintf("%.9f", b$`26`$peaks[1, 1])
system.time(b <-
              readAllScanMS2("/mnt/d/work/202202/testRAW/201019_CP_6801_E50.FT2"))

a=readAllScanMS2("/mnt/d/work/202203/ecoliPct1/ft/Pan_022822_X1.FT2")
a=readAllScanMS1("/mnt/d/work/202203/ecoliPct1/ft/Pan_022822_X1.FT1")

a=readSip("/mnt/d/ubuntuShare/EcoliSIP/sip/Pan_022822_X1.C13_0Pct.sip")
a=readSips("/mnt/d/ubuntuShare/EcoliSIP/sip/")

a=getUnfilteredPeptides("/mnt/d/ubuntuShare/EcoliSIP/sip/sip0")
a=getUnfilteredPSMs("/mnt/d/ubuntuShare/EcoliSIP/sip/")
a=getUnfilteredPSMs("/mnt/d/ubuntuShare/EcoliSIP/sip/sip0")

a=getFilterThreshold("/mnt/d/ubuntuShare/EcoliSIP/sip/sip0",0.01)
```

## for plot

```{r}
a<-getPrecursorSpectra("KHRIP",2)
plot(a)
a<-getSipPrecursorSpectra("KHRIPCDRK", "C13", 0.55, 2)
plot(a)
a<-getSipBYionSpectra("KHRIPKR", "C13", 0.5, 1)
plot(a)
```
