#! /bin/sh
module load \
    CMake/3.15.3-GCCcore-8.3.0 \
    OpenMPI/3.1.4-GCC-8.3.0 \
    gperftools/2.7.90-GCCcore-8.3.0
case $1 in
    "clean")  
        rm -rf build
        mkdir build
        rm -rf bin
        mkdir bin
        ;;
    "build") 
        cd build 
        cmake ..
        make -j6
        ;;
    "make") 
        cd build 
        make
        ;;
    "run")
        cd bin 
        ./SiprosV3omp
        ./SiprosV3mpi
        ;;
    *)  
        ./make "build"
    ;;
esac