---
title: "compareDifferentSoftwares"
author: "xyz"
date: '2022-07-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(ggplot2)
library(tidyr)
```

```{r}
df <- read_xlsx("/mnt/d/work/202207/SIP protein different soft identification.xlsx", n_max = 10)
df <- cbind(IX=paste0(df$`13C abundance (%)`,df$Software),df)
df$IX <- factor(df$IX,levels=df$IX)

psms <- cbind(df[, 1:3], PSMs = df$PSMs)
peptides <- cbind(df[, 1:3], Peptides = df$Peptides)
proteins <- cbind(df[, 1:3], Proteins = df$Proteins)


xName <- c("","1.07","","","25","","","50","")
xTitle <- ggplot2::xlab(expression(""^13*"C"*" (%)"))
geom <- geom_bar(
  stat = "identity",
  position = "dodge",
  width = 0.8,
  col = "black"
)
theme2 <- theme(
        # axis.text = ggplot2::element_blank(),
        axis.ticks = ggplot2::element_blank(),
        # axis.title = ggplot2::element_blank(),
        panel.grid = ggplot2::element_blank(),
        panel.background = ggplot2::element_blank(),
        legend.key = ggplot2::element_blank(),
        panel.border = ggplot2::element_rect(
          fill = NA,
          color = "grey10",
          linetype = 1,
          size = 0.5
        ),
        text = ggplot2::element_text(size = 15)
      )
ggplot(psms, aes(x = IX, y = PSMs, fill = Software)) + geom + theme2 + xTitle  +
  scale_x_discrete(labels = xName)
ggsave("psms.pdf", width = 10, height = 5)

ggplot(peptides, aes(x = IX, y = Peptides, fill = Software)) + geom + theme2 + xTitle  +
  scale_x_discrete(labels = xName)
ggsave("peptides.pdf", width = 10, height = 5)

ggplot(proteins, aes(x = IX, y = Proteins, fill = Software)) + geom + theme2 + xTitle  +
  scale_x_discrete(labels = xName)
ggsave("proteins.pdf", width = 10, height = 5)
```
