---
title: "AveragineNitrogen"
author: "xyz"
date: "2022-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(Aerith)
library(stringr)
library(stringi)
```


#### simulate mass window center

percent:

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100

center:

0,0,0,0,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,6,6,6,-5,-5,-5,-5,-5,-4,-4,-4,-4,-4,-4,-4,-4,-4,-3,-3,-3,-3,-3,-3,-3,-3,-2,-2,-2,-2,-2,-2,-2,-2,-2,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0

revised center by real data:

0,0,0,0,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,7,7,7,-1,-5,-5,-5,-5,-4,-4,-4,-4,-4,-4,-4,-4,-4,-3,-3,-3,-3,-3,-3,-3,-3,-2,-2,-2,-2,-2,-2,-2,-2,-2,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0

```{r}
getResidueMass <- function(residue, pct) {
  spectra <- residue_peak_calculator_DIY(residue, "N15", pct)
  mass <- spectra$Mass[which.max(spectra$Prob)]
  return(mass)
}
getSeqMass <- function(pepSeq, pct) {
  spectra <- precursor_peak_calculator_DIY(pepSeq, "N15", pct)
  mass <- spectra$Mass[which.max(spectra$Prob)]
  return(mass)
}

# get precursor mass by sum of highest peak mass of residue
monoAveragineSeqs <- rep("a", 101)
pcts <- seq(0, 100) / 100
monoAveragineMasses <-
  mapply(getResidueMass, monoAveragineSeqs, pcts)
monoAveragineMassMat <- 6:60 %*% t(monoAveragineMasses)
colnames(monoAveragineMassMat) <- pcts
rownames(monoAveragineMassMat) <- 6:60
monoAveragineMassMat <-
  monoAveragineMassMat + getResidueMass("Nterm", 0) + getResidueMass("Cterm", 0)

# get precursor mass by accurate calculation
pcts <- seq(0, 100) / 100
pcts <- rep(pcts, each = 60 - 6 + 1)
monoAveragineSeqs <- strrep("a", 6:60)
monoAveragineSeqs <- rep(monoAveragineSeqs, 101)
AveragineMasses <- mapply(getSeqMass, monoAveragineSeqs, pcts)
AveragineMassesMat <- matrix(AveragineMasses, nrow = 60 - 6 + 1)
colnames(AveragineMassesMat) <- seq(0, 100) / 100
rownames(AveragineMassesMat) <- 6:60

# get window shift
windowsMat <- (AveragineMassesMat - monoAveragineMassMat)
write.csv(windowsMat, "windowsMat.csv")
pdf("AveragineMass and monoAveragineMass.pdf")
plot(x = 0:100, y = AveragineMassesMat["11", ], type = "l", col = "red")
lines(x = 0:100, y = monoAveragineMassMat["11", ], type = "l", col = "green")
dev.off()
# get peptides with 11 residues' mass center
center <- round(windowsMat["11", ])
paste(names(center), collapse = ",")
paste(unname(center), collapse = ",")
paste(0:100, collapse = ",")
pdf("pct and mass window center.pdf")
plot(x = 0:100, y = center)
dev.off()
```

#### simulate masswindow length

percent:

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100

half width:

2,2,2,2,2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,3,3,3,3,2,2

1/1.5 width by real data:

3,3,3,3,3,3,3,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,5,5,5,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,7,7,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,5,5,5,5,6,6,6,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,4,4,4,4,3,3


```{r}
getSeqMassWidth <- function(pepSeq, pct) {
  spectra <- precursor_peak_calculator_DIY(pepSeq, "N15", pct)
  return(sum(spectra$Prob > 0.01))
}
pcts <- seq(0, 100) / 100
pcts <- rep(pcts, each = 60 - 6 + 1)
monoAveragineSeqs <- strrep("a", 6:60)
monoAveragineSeqs <- rep(monoAveragineSeqs, 101)
AveragineWidth <- mapply(getSeqMassWidth, monoAveragineSeqs, pcts)
AveragineWidthMat <- matrix(AveragineWidth, nrow = 60 - 6 + 1)
colnames(AveragineWidthMat) <- seq(0, 100) / 100
rownames(AveragineWidthMat) <- 6:60
# get peptides with 11 residues' mass width
# width <- round(AveragineWidthMat["11", ] / 2)
# let the width longer
width <- round(AveragineWidthMat["11", ] / 1.5)
paste(names(width), collapse = ",")
paste(unname(width), collapse = ",")
paste(0:100, collapse = ",")
```

### generate configs with different mass center

```{r}
generateOneCFG("/mnt/d/Projects/Aerith/extdata/SiprosConfig.cfg", "configs", "N", 50, -3, 2)
generateCFGs("/mnt/d/Projects/Aerith/extdata/SiprosConfig.cfg", "configs", "N")
```
### N15 pct50

```{r}
psm <-
  read.table(
    "AMD_StandardEnrichment_SampleBeta_50Percent15N_Velos_OrbiMS2_Run2_020110.psm.txt",
    header = T
  )
psm <- arrange(psm, Filename, desc(Score))
massError <- round(psm$MeasuredParentMass - psm$CalculatedParentMass)
pct <- psm$SearchName
pct <-
  as.numeric(str_sub(str_split(pct, "_", simplify = T)[, 2], 1, -4))
errorDf <- as.data.frame(table(massError, pct))
errorDf <- arrange(errorDf, desc(pct), desc(Freq))
massError2 <- c()
for (i in 30:70) {
  massError2 <- c(massError2, as.character(errorDf[errorDf$pct == i, ]$massError[1]))
}
errorDf2<-data.frame(pct=30:70,massError=massError2)

ft2 <-
  readAllScanMS2("/mnt/d/work/202208/AMD pct50/AMD_StandardEnrichment_SampleBeta_50Percent15N_Velos_OrbiMS2_Run2_020110_02.FT2")

pct <- pct / 100
psm <- psm[1:10, ]
scanNumbers <- psm$ScanNumber
pep <- psm$OriginalPeptide
sort(table(str_length(pep) - 2), decreasing = T)
realScans <- getRealScansWithCharges(ft2, scanNumbers)

sp <- realScans[[1]]@spectra
revPep <- paste0("[", stri_reverse(str_sub(pep[1], 2, -2)), "]")
scorePSM(sp$Mass, sp$Prob, sp$Charge, pep[1], "N15", pct[1])
scorePSM(sp$Mass, sp$Prob, sp$Charge, revPep, "N15", pct[1])
scorePSMold(sp$Mass, sp$Prob, sp$Charge, pep[1], "N15", pct[1])
scorePSMold(sp$Mass, sp$Prob, sp$Charge, revPep, "N15", pct[1])

sp <- realScans[[2]]@spectra
revPep <- paste0("[", stri_reverse(str_sub(pep[2], 2, -2)), "]")
scorePSM(sp$Mass, sp$Prob, sp$Charge, pep[2], "N15", pct[2])
scorePSM(sp$Mass, sp$Prob, sp$Charge, revPep, "N15", pct[2])
scorePSMold(sp$Mass, sp$Prob, sp$Charge, pep[2], "N15", pct[2])
scorePSMold(sp$Mass, sp$Prob, sp$Charge, revPep, "N15", pct[2])

sp <- realScans[[3]]@spectra
revPep <- paste0("[", stri_reverse(str_sub(pep[3], 2, -2)), "]")
scorePSM(sp$Mass, sp$Prob, sp$Charge, pep[3], "N15", pct[3])
scorePSM(sp$Mass, sp$Prob, sp$Charge, revPep, "N15", pct[3])
scorePSMold(sp$Mass, sp$Prob, sp$Charge, pep[3], "N15", pct[3])
scorePSMold(sp$Mass, sp$Prob, sp$Charge, revPep, "N15", pct[3])

sp <- realScans[[4]]@spectra
revPep <- paste0("[", stri_reverse(str_sub(pep[4], 2, -2)), "]")
scorePSM(sp$Mass, sp$Prob, sp$Charge, pep[4], "N15", pct[4])
scorePSM(sp$Mass, sp$Prob, sp$Charge, revPep, "N15", pct[4])
scorePSMold(sp$Mass, sp$Prob, sp$Charge, pep[4], "N15", pct[4])
scorePSMold(sp$Mass, sp$Prob, sp$Charge, revPep, "N15", pct[4])
```

# test .sip file

96Pct.sip

*Day3Rep1*03.C13* *Day3Rep1*04.C13* *Day3Rep2*11.C13* *Day3Rep3*01.C13* *Day3Rep3*08.C13* *Day3Rep3*10.C13* *Day8Rep1*07.C13* *Day8Rep1*09.C13*

8 slave process dead

```{r}
sip <- read.table("sipList.txt")
sip <- as.data.frame(str_split(sip$V1, "_", simplify = T))
pct <- table(sip$V8)
pct[pct == 58]
ft <- table(paste0("*", sip$V3, "*", sip$V7, "*"))
ft[ft == 100]
```

