// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// peak_calculator
DataFrame peak_calculator(CharacterVector AAstr);
RcppExport SEXP _AAisoPeak_peak_calculator(SEXP AAstrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type AAstr(AAstrSEXP);
    rcpp_result_gen = Rcpp::wrap(peak_calculator(AAstr));
    return rcpp_result_gen;
END_RCPP
}
// peak_calculator_DIY
DataFrame peak_calculator_DIY(CharacterVector AAstr, CharacterVector Atom, NumericVector Prob);
RcppExport SEXP _AAisoPeak_peak_calculator_DIY(SEXP AAstrSEXP, SEXP AtomSEXP, SEXP ProbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type AAstr(AAstrSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type Atom(AtomSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Prob(ProbSEXP);
    rcpp_result_gen = Rcpp::wrap(peak_calculator_DIY(AAstr, Atom, Prob));
    return rcpp_result_gen;
END_RCPP
}
// calc_sum
double calc_sum(NumericVector x);
RcppExport SEXP _AAisoPeak_calc_sum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_sum(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AAisoPeak_peak_calculator", (DL_FUNC) &_AAisoPeak_peak_calculator, 1},
    {"_AAisoPeak_peak_calculator_DIY", (DL_FUNC) &_AAisoPeak_peak_calculator_DIY, 3},
    {"_AAisoPeak_calc_sum", (DL_FUNC) &_AAisoPeak_calc_sum, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_AAisoPeak(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
