# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' getUnfilteredPSMs
#' @param workingPath a full path with .sip files in it
#' @return a dataframe of unique PSMs and whether it is decoy sequence
#' @export
getUnfilteredPSMs <- function(workingPath) {
    .Call(`_Aerith_getUnfilteredPSMs`, workingPath)
}

#' getUnfilteredPeptides
#' @param workingPath a full path with .sip files in it
#' @return a dataframe of unique peptides and whether it is decoy sequence
#' @export
getUnfilteredPeptides <- function(workingPath) {
    .Call(`_Aerith_getUnfilteredPeptides`, workingPath)
}

#' getFilterThreshold
#' @param workingPath a full path with .sip files in it
#' @return a dataframe about filter threshold and FDR results
#' @export
getFilterThreshold <- function(workingPath, OverallThreshold) {
    .Call(`_Aerith_getFilterThreshold`, workingPath, OverallThreshold)
}

#' Simple peak calculator of natural isotopic distribution
#' @param AAstr a CharacterVector
#' @export
precursor_peak_calculator <- function(AAstr) {
    .Call(`_Aerith_precursor_peak_calculator`, AAstr)
}

#' Simple peak calculator of user defined isotopic distribution of one peptide
#' @param AAstr a CharacterVector
#' @param Atom a CharacterVector C13 or N15
#' @param Prob a NumericVector for its abundance
#' @export
precursor_peak_calculator_DIY <- function(AAstr, Atom, Prob) {
    .Call(`_Aerith_precursor_peak_calculator_DIY`, AAstr, Atom, Prob)
}

#' peak calculator of B Y ione from of one peptide using user defined isotopic distribution
#' @param AAstr a CharacterVector
#' @param Atom a CharacterVector C13 or N15
#' @param Prob a NumericVector for its abundance
#' @export
BYion_peak_calculator_DIY <- function(AAstr, Atom, Prob) {
    .Call(`_Aerith_BYion_peak_calculator_DIY`, AAstr, Atom, Prob)
}

#' readOneScanMS2
#' @param ftFile a ft2 file's full path
#' @param scanCount the scanCount'th scan
#' @export
readOneScanMS2 <- function(ftFile, scanCount) {
    .Call(`_Aerith_readOneScanMS2`, ftFile, scanCount)
}

#' readOneScanMS1
#' @param ftFile a ft1 file's full path
#' @param scanCount the scanCount'th scan
#' @export
readOneScanMS1 <- function(ftFile, scanCount) {
    .Call(`_Aerith_readOneScanMS1`, ftFile, scanCount)
}

#' read MS1 scans with scanNumber as index
#' @param ftFile a ft1 file's full path
#' @return a list of MS1 scans with names of scan number
#' @examples
#' ft1 <- readAllScanMS1("demo.ft1")
#' @export
readScansMS1 <- function(ftFile, scanCount) {
    .Call(`_Aerith_readScansMS1`, ftFile, scanCount)
}

#' readAllScanMS1
#' @param ftFile a ft1 file's full path
#' @export
readAllScanMS1 <- function(ftFile) {
    .Call(`_Aerith_readAllScanMS1`, ftFile)
}

#' readScansMS2
#' @param ftFile a ft2 file's full path
#' @param scanNumber the scanNumber th scan
#' @export
readScansMS2 <- function(ftFile, scanCount) {
    .Call(`_Aerith_readScansMS2`, ftFile, scanCount)
}

#' read MS2 scans with scanNumber as index
#' @param ftFile a ft1 file's full path
#' @return a list of MS2 scans with names of scan number
#' @examples
#' ft2 <- readAllScanMS2("demo.ft2")
#' @export
readAllScanMS2 <- function(ftFile) {
    .Call(`_Aerith_readAllScanMS2`, ftFile)
}

#' readSip
#' @param sipFile a .sip file's full path
#' @export
readSip <- function(sipFile) {
    .Call(`_Aerith_readSip`, sipFile)
}

#' readSips
#' @param workingPath a full path with .sip files in it
#' @export
readSips <- function(workingPath) {
    .Call(`_Aerith_readSips`, workingPath)
}

#' Simple sum
#' @param x a numeric vector
#' @export
calc_sum <- function(x) {
    .Call(`_Aerith_calc_sum`, x)
}

#' test ftFileReader
#' @param ftFile a ft file's full path
#' @export
test_ftFileReader <- function(ftFile) {
    invisible(.Call(`_Aerith_test_ftFileReader`, ftFile))
}

