---
title: "ecoliPCT0"
output: html_document
date: "2022-08-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(dplyr)
library(Aerith)
library(stringr)
```

```{r}
proPct <-
    read.table("iso_1_6/Pan_062822_X.pro.cluster.txt",
               sep = "\t",
               quote = "",
               header = T)
plotProSipPct <- function(proPath) {
  proPct <-
    read.table(proPath,
               sep = "\t",
               quote = "",
               header = T)
  proPct<-proPct[stringr::str_detect(proPct$ProteinID, "Rev_",
                                                         negate = T),]
  proPct<-proPct[stringr::str_detect(proPct$ProteinID, "_SHEEP",
                                                         negate = T),]
  proPct<-proPct[stringr::str_detect(proPct$ProteinID, "_HUMAN",
                                                         negate = T),]
  proPct<-proPct[stringr::str_detect(proPct$ProteinID, "_PIG",
                                                         negate = T),]
  FDR <- readLines(proPath, 44)[44]
  FDR <- as.numeric(stringr::str_extract(FDR, "[0-9]\\.[0-9]+"))
  output <- paste0("FDR: ", round(FDR, 3), "\n")
  output <-
    paste0(output, "Proteins: ", nrow(proPct), "\n")
  output <-
    paste0(output,
           "Average Pct: ",
           round(mean(proPct$AverageEnrichmentLevel), 3),
           "%\n")
  output <-
    paste0(output,
           "Median Pct: ",
           round(median(proPct$AverageEnrichmentLevel), 3),
           "%\n")
  output <-
    paste0(output, "Pct SD: ", round(sd(proPct$AverageEnrichmentLevel), 3), "%")
  cat(output)
  x <- data.frame(Abundance = proPct$AverageEnrichmentLevel)
  p <-
    ggplot2::ggplot(data = x,
                    mapping = aes(x = Abundance)) +
    ggplot2::geom_histogram(binwidth = 1,
                            color = I("black")) +
    xlab("SIP abundance (%)") +
    ylab("Protein Count") +
    theme(text = element_text(size = 15))
  p
}
```


FDR: 0.071
Proteins: 1929
Average Pct: 1.321%
Median Pct: 1%
Pct SD: 3.817%

```{r}
p <-
  plotProSipPct(
    "iso_1_6/Pan_062822_X.pro.cluster.txt"
  )
p
ggsave("EcoliPct0.pdf",
       width = 8,
       height = 6)
```

FDR: 0.069
Proteins: 1915
Average Pct: 1.036%
Median Pct: 1%
Pct SD: 0.945%

```{r}
p <-
  plotProSipPct(
    "iso_5/Pan_062822_X.pro.cluster.txt"
  )
p
ggsave("EcoliPct0.pdf",
       width = 8,
       height = 6)
```

